### ISSUE TITLE
Panic when comparing structs with time.Time value and CompareUnexportedFields is true

### ISSUE THREAD

**Issue by andrewmunro** [go-test/deep#18]
I have a large struct I am comparing which contains unexported fields and time.Time values.
When comparing this struct, I get the following error:

```
panic: reflect: reflect.Value.Call using value obtained using unexported field [recovered]
```

By reading https://github.com/martini-contrib/encoder/issues/9 and some hacky logging, I've narrowed it down to structs that contain time.Time values when using the `CompareUnexportedFields` option.

Reproduction code:

```
package main

import (
	"testing"
	"time"

	"github.com/go-test/deep"
)

func init() {
	deep.CompareUnexportedFields = true
}

type Foo struct {
	t time.Time
}

func TestFoo(t *testing.T) {
	a := &Foo{
		t: time.Now(),
	}

	b := &Foo{
		t: time.Now(),
	}

	if diff := deep.Equal(a, b); diff != nil {
		t.Errorf("Diff: \n%v", diff)
	}
}
```

Full stacktrace:

```
--- FAIL: TestFoo (0.00s)
panic: reflect: reflect.Value.Call using value obtained using unexported field [recovered]
	panic: reflect: reflect.Value.Call using value obtained using unexported field

goroutine 6 [running]:
testing.tRunner.func1(0xc4200c00f0)
	/usr/local/Cellar/go/1.10/libexec/src/testing/testing.go:742 +0x29d
panic(0x114a060, 0xc420064570)
	/usr/local/Cellar/go/1.10/libexec/src/runtime/panic.go:505 +0x229
reflect.flag.mustBeExported(0x22b3)
	/usr/local/Cellar/go/1.10/libexec/src/reflect/value.go:218 +0x145
reflect.Value.Call(0x117fe80, 0xc42000a0e0, 0x22b3, 0xc4200cf238, 0x1, 0x1, 0xc42000a0e0, 0x22b3, 0x0)
	/usr/local/Cellar/go/1.10/libexec/src/reflect/value.go:307 +0x46
foo/vendor/github.com/go-test/deep.(*cmp).equals(0xc4200cfec8, 0x117fe80, 0xc42000a0e0, 0x1b9, 0x117fe80, 0xc42000a100, 0x1b9, 0x2)
	/Users/amu19/go/src/foo/vendor/github.com/go-test/deep/deep.go:147 +0x28ed
foo/vendor/github.com/go-test/deep.(*cmp).equals(0xc4200cfec8, 0x115e3c0, 0xc42000a0e0, 0x199, 0x115e3c0, 0xc42000a100, 0x199, 0x1)
	/Users/amu19/go/src/foo/vendor/github.com/go-test/deep/deep.go:184 +0x1598
foo/vendor/github.com/go-test/deep.(*cmp).equals(0xc420060ec8, 0x115e3c0, 0xc42000a0e0, 0x199, 0x1144800, 0xc42000a100, 0x16, 0x0)
	/Users/amu19/go/src/foo/vendor/github.com/go-test/deep/deep.go:139 +0x394
foo/vendor/github.com/go-test/deep.Equal(0x1144800, 0xc42000a0e0, 0x1144800, 0xc42000a100, 0x1241681, 0x38, 0x2d2)
	/Users/amu19/go/src/foo/vendor/github.com/go-test/deep/deep.go:77 +0x262
foo/internal/model/customer.TestFoo(0xc4200c00f0)
	/Users/amu19/go/src/foo/internal/model/customer/customer_test.go:27 +0x11e
testing.tRunner(0xc4200c00f0, 0x118e280)
	/usr/local/Cellar/go/1.10/libexec/src/testing/testing.go:777 +0xd0
created by testing.(*T).Run
	/usr/local/Cellar/go/1.10/libexec/src/testing/testing.go:824 +0x2e0
```

**Comment by daniel-nichter** [comment]
Fixed in cceb0f4.  As it turns out, Go does not allow calling funcs from unexported fields:
In `reflect/value.go`:
```go
func (v Value) Call(in []Value) []Value {
    v.mustBe(Func)
    v.mustBeExported()
    return v.call("Call", in)
}

// mustBeExported panics if f records that the value was obtained using
// an unexported field.
func (f flag) mustBeExported() {
	if f == 0 {
		panic(&ValueError{methodName(), 0})
	}
	if f&flagRO != 0 {
		panic("reflect: " + methodName() + " using value obtained using unexported field")
	}
}
```

So we want `f&flagRO != 0`, which happens to be what this tests:
```go
// CanInterface reports whether Interface can be used without panicking.
func (v Value) CanInterface() bool {
	if v.flag == 0 {
		panic(&ValueError{"reflect.Value.CanInterface", Invalid})
	}
	return v.flag&flagRO == 0
}
```

I don't think this is the intended purpose of `CanInterface`, but it works and it allows the code to stay simple.

Since `Equal` can't be called, the code descends into the unexported `time.Time` fields and yields a diff like `[t.wall: 13740788835924462040 != 13740788836998203864 t.ext: 1447549 != 1001447549]`.  Less friendly by technically accurate: the two `time.Time` aren't equal because their internal values aren't the same.
